const exercises = [
  'Caminata',
  'Crunches',
  'Plancha lateral',
  'Mountain climbers',
  'Sentadillas con salto',
  'Flexiones',
  'Peso muerto',
  'Fondos',
  'Plancha con elevación de pierna',
  'Ciclismo',
  'Russian twists',
  'Levantamiento de piernas acostada',
  'Superman',
  'Zancadas',
  'Flexiones de tríceps',
  'Remo con barra',
  'Elevación lateral con mancuernas',
  'Abdominales bicicleta',
  'Abdominales en V',
  'Estocadas',
  'Elevación de talones',
  'Flexiones inclinadas',
  'Remo con mancuerna',
  'Plancha',
  'Sentadillas con peso',
  'Crunches cruzados',
  'Press de hombros con mancuernas',
  'Zancadas con mancuernas',
  'Sentadillas',
  'Press de banca',
  'Pull-ups',
  'Curl de bíceps con barra',
  'Press militar con mancuernas',
  'Press de piernas',
  'Fondos en máquina',
  'Curl de bíceps con mancuernas',
  'Press de hombros con barra',
  'Curl de bíceps alterno',
  'Extensiones de tríceps con mancuerna',
  'Cardio (Correr)',
  'Elevaciones laterales con mancuernas',
  'Extensiones de tríceps en polea alta',
  'Flexiones de rodillas',
  'Flexiones de tríceps en banco',
  'Peso muerto con barra',
  'Levantamiento de piernas colgando',
  'Flexiones de brazos',
  'Flexiones de pecho',
  'Peso muerto rumano',
  'Sentadillas con barra',
  'Hip Thrust',
  'Press de banca con mancuernas',
  'Trote',
  'Press de banca con barra',
  'Press militar con barra',
  'Levantamiento de piernas acostado',
  'Burpees',
  'Fondos en paralelas',
  'Curl de martillo',
  'Elevación frontal con mancuernas',
  'Press de banca inclinado',
  'Press militar sentado con mancuernas',
  'Curl de bíceps martillo',
  'Crunches inversos',
  'Pull-Ups',
  'Plancha ponderada',
  'Dips con lastre',
  'Remo con barra T',
  'Curl de bíceps con barra Z',
  'Crunches con peso',
  'Hip Thrust con barra',
  'Elevación de talones con peso',
  'Sentadillas pesadas',
  'Press militar',
  'Extensión de tríceps en polea alta',
  'Elevaciones de gemelos en máquina',
  'Encogimientos de hombros con mancuernas',
  'Elevaciones de gemelos con peso',
  'Elevaciones laterales de pierna',
  'Saltos de cuerda',
  'Flexiones en barra fija',
];
