export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PLAN_REPOSITORY = 'PLAN_REPOSITORY';
export const EXERCISE_REPOSITORY = 'EXERCISE_REPOSITORY';
export const PLAN_DAY_REPOSITORY = 'PLAN_DAY_REPOSITORY';
export const PLAN_DAY_EXERCISE_REPOSITORY = 'PLAN_DAY_EXERCISE_REPOSITORY';

export const JWT_SECRET = process.env.JWT_SECRET;

export const IS_PUBLIC = 'isPublic';
